#pragma once
#include <Windows.h>
#include <string>
#include <sstream>
#include <list>
#include <vector>
#include <memory>
#include <iostream>
#include <algorithm>
#include <iterator>
#include <mutex>
#include <functional>
#include <iterator>
#include <map>
#include <thread>
#include <cctype>
#include <fstream>
#include <atomic>
